### ISSUE TITLE
Sort parameter issue

### ISSUE THREAD

**Issue by kuyazee** [jakejosol/warp-server#1]
for **/users** and **/classes/$className** the sorting url parameter differs.

**/users**
This works `$defaultUrl/users?order=[{"created_at":-1}]`
This doesn't `$defaultUrl/users?sort=[{"created_at":-1}]`

**/classes/$className**
This works `$defaultUrl/classes/$className?sort=[{"created_at":-1}]`
This doesn't `$defaultUrl/classes/$className?order=[{"created_at":-1}]`

**Comment by jakejosol** [comment]
Thanks for the heads up. This has been resolved with the patch 3.0.3
